[versions]
morphe-patcher = "1.10.0"
morphe-patches-library = "1.6.2"
instagram-morphe-patches-library = "1.1.0"
#noinspection GradleDependency
smali = "d92701d947"
gson = "2.14.0"
annotation = "1.9.1"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
morphe-patches-library = { module = "app.morphe:morphe-patches-library", version.ref = "morphe-patches-library" }
morphe-extensions-library = { module = "app.morphe:morphe-extensions-library", version.ref = "morphe-patches-library" }
instagram-morphe-patches-library = { module = "app.morphe:instagram-morphe-patches-library", version.ref = "instagram-morphe-patches-library" }
instagram-morphe-extensions-library = { module = "app.morphe:instagram-morphe-extensions-library", version.ref = "instagram-morphe-patches-library" }

[plugins]
android-library = { id = "com.android.library" }
